### ISSUE TITLE
Highlighting not working properly

### ISSUE THREAD

**Issue by GotAnAccount** [appliedengdesign/vscode-gcode-syntax#40]
**Describe the bug**
Highlighting is applied on letters only in whole words for a LinuxCNC g-code file. 

For example:
    o<gotots> sub
Both letters "t" are highlited blue and should not.

**To Reproduce**

1. Simply open a g-code file and view.
 
**Expected behavior**
No highting should normally happen for these words.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/55237040/174478784-54abb668-8a41-4815-9cea-fa1b545d5a3e.PNG)

**Environment / Version:**
Version : 1.68.1
Validation : 30d9c6cd9483b2cc586687151bcbcd635f373630
Date : 2022-06-14T12:48:58.283Z
Electron : 17.4.7
Chromium: 98.0.4758.141
Node.js : 16.13.0
V8 : 9.8.177.13-electron.0
Système d’exploitation : Windows_NT x64 10.0.19044

**Additional context**
g-code file from this site: https://www.projectsbybrian.tech/s/PrintNC.zip
open file from "macros" folder.

**Comment by mikecentola** [comment]
I'll look into this ASAP. Thanks!

**Comment by mikecentola** [comment]
Fixed in v0.7.2

**Comment by GotAnAccount** [comment]
Hi,

Thank you for the changes. I updated it (v0.7.2) and I can still see some use cases where the problem still seems to exist.

Here is the screenshot for the "while" and "endsub" cases:
![image](https://user-images.githubusercontent.com/55237040/176883889-4cf857b6-1eff-41e6-a5a7-742845da2ce9.png)

Here is the screenshot for the "if" and "gt 0" and another "endsub":
![image](https://user-images.githubusercontent.com/55237040/176884140-4e3a83c3-9570-46bb-8794-e30abd9e93d1.png)

**Comment by mikecentola** [comment]
Okay I'll push changes for the t/f/b regex tonight or tomorrow

**Comment by mikecentola** [comment]
@GotAnAccount Just pushed v0.7.3 with a bunch of fixes that should make editing the LinuxCNC ngc templates much nicer and more colorful :)

Let me know if it's working and we can close this issue out!

**Comment by GotAnAccount** [comment]
OK, confirmed the changes did fix the issue. 

Thanks Mike for your excellent work!
